config/routes.rb
Rails.application.routes.draw do

  get 'insights/dashboard'

  get 'insights/leads'

  get 'insights/editlisting'

  devise_for :franchises, :controllers => {:registrations => "franchises/registrations"}
  devise_for :users, :controllers => {:registrations => "users/registrations"}

  get 'footerlinks/editlisting'
  get 'footerlinks/franchisorinfo'
  get 'footerlinks/aboutus'
  get 'footerlinks/contactus'
  get 'footerlinks/toc'
  post 'footerlinks/contactcreate'

  get '/sitemap.xml.gz', to: 'sitemaps#show'
  
  get 'lead_form/new'
  get 'lead_form/create'

  get 'blog', to: 'posts#index'
  get 'posts/new'
  get 'posts/edit'
  get 'posts/show'

  get 'events/', to: 'events#index'
  get 'events/new'
  get 'events/show'
  get 'events/edit'

  get 'industry/index'
  get 'industry/accounting'
  get 'industry/agriculture'
  get 'industry/automotive'
  get 'industry/beverage'
  get 'industry/B2B'
  get 'industry/cafeandcoffee'
  get 'industry/care'
  get 'industry/chemical'
  get 'industry/childrenandbabies'
  get 'industry/cleaning'
  get 'industry/communications'
  get 'industry/computers'
  get 'industry/construction'
  get 'industry/consultancy'
  get 'industry/logistics'
  get 'industry/educationandtraining'
  get 'industry/electrical'
  get 'industry/entertainment'
  get 'industry/enviromental'
  get 'industry/estateagents'
  get 'industry/fashion'
  get 'industry/financial'
  get 'industry/food'
  get 'industry/health'
  get 'industry/hirerental'
  get 'industry/hospitality'
  get 'industry/indoorpropertyservices'
  get 'industry/outdoorpropertyservices'
  get 'industry/internet'
  get 'industry/legal'
  get 'industry/manafacture'
  get 'industry/pets'
  get 'industry/promotional'
  get 'industry/print'
  get 'industry/repairandmaintenance'

  get 'industry/investment1'
  get 'industry/investment2'
  get 'industry/investment3'
  get 'industry/investment4'

  get 'admin/overview'
  get 'admin/listings'
  get 'admin/events'
  get 'admin/moneyzone'

  resources :listings, :path => "franchise" do
     member do
       get :leadcreate
       post :storycreate
     end
  end

  resources :admin

  resources :posts, :path => "blog"
  post 'posts/subscribe' => 'posts#subscribe'

  resources :events

  devise_for :admins

  root to: 'home#index'

  get 'home/index'
  get 'home/search'
  get 'comingsoon', to: "home#comingsoon"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates_acceptance_of :toc, :on => :create, :accept => true
	validates :fullname, :email, :query, presence: true
	validates :fullname, :email, :query, length: {minimum: 0, maximum: 5000}
end

app/models/event.rb
class Event < ActiveRecord::Base
  extend FriendlyId
  friendly_id :eventname, use: :slugged
end

app/models/franchise.rb
class Franchise < ActiveRecord::Base
	has_one :listing
 	accepts_nested_attributes_for :listing
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/lead.rb
class Lead < ActiveRecord::Base
	belongs_to :listing
end

app/models/listing.rb
require 'elasticsearch/model'

class Listing < ActiveRecord::Base
  belongs_to :franchise, :dependent => :delete
  has_many :leads
  has_many :stories

  extend FriendlyId
  friendly_id :franchisename, use: :slugged

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

	is_impressionable



def self.search(query)
  __elasticsearch__.search(
    {
      query: {
        multi_match: {
          query: query,
          fields: ['franchisename^10', 'longdescription']
        }
      }
    }
  )
end

end

# Delete the previous articles index in Elasticsearch
Listing.__elasticsearch__.client.indices.delete index: Listing.index_name rescue nil
 
# Create the new index with the new mapping
Listing.__elasticsearch__.client.indices.create \
  index: Listing.index_name,
  body: { settings: Listing.settings.to_hash, mappings: Listing.mappings.to_hash }
 
# Index all article records from the DB to Elasticsearch
Listing.import

app/models/post.rb
class Post < ActiveRecord::Base

  extend FriendlyId
  friendly_id :title, use: :slugged

	is_impressionable

end

app/models/story.rb
class Story < ActiveRecord::Base
	belongs_to :listing
	
	validates_acceptance_of :toc, :on => :create, :accept => true
  validates :fullname, :email, :jobrole, :story, presence: true
  validates :story, uniqueness: true
  validates :fullname, :email, :jobrole, length: { minimum: 5, maximum: 150 }
  validates :story, length: { minimum: 150, maxium: 360 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/footerlinks_helper.rb
module FooterlinksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/industry_helper.rb
module IndustryHelper
end

app/helpers/insights_helper.rb
module InsightsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/panel_helper.rb
module PanelHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sitemaps_helper.rb
module SitemapsHelper
end

app/views/admin/events.html.erb
   <%= form_for(@newevent) do |event| %>
      <%= event.text_field :eventname, :placeholder => "Event Name", onfocus: "this.placeholder = ''", onblur: "this.placeholder = 'Event Name'", class: "eventnewform" %>
      <div class="row">
      	<div class="large-11 columns">
		      <%= event.text_field :startdate, :placeholder => "Start Date (DD/MM/YYYY)", onfocus: "this.placeholder = ''", onblur: "this.placeholder = 'Start Date (DD/MM/YYYY)'", class: "eventnewform" %>
		    </div>
		    <div class="large-2 columns">
		    	<br>
		    </div>
			  <div class="large-11 columns">
		      <%= event.text_field :enddate, :placeholder => "End Date (DD/MM/YYYY)", onfocus: "this.placeholder = ''", onblur: "this.placeholder = 'End Date (DD/MM/YYYY)'", class: "eventnewform" %>
		    </div>
	      <%= event.text_area :shortdescription, :placeholder => "Short Description", onfocus: "this.placeholder = ''", onblur: "this.placeholder = 'Short Description'", class: "eventnewform charlimit2 margin0b" %>
        <div class="charcount2 margin1b text-right"></div>
	      <%= event.text_field :region, :placeholder => "Region", onfocus: "this.placeholder = ''", onblur: "this.placeholder = 'Region'", class: "eventnewform" %>
	      <%= event.text_field :postcode, :placeholder => "Postal Code", onfocus: "this.placeholder = ''", onblur: "this.placeholder = 'Postal Code'", class: "eventnewform" %>
	      <%= event.text_field :website, :placeholder => "Event Website", onfocus: "this.placeholder = ''", onblur: "this.placeholder = 'Event Website'", class: "eventnewform" %>
	      <%= event.text_field :long, :placeholder => "long", onfocus: "this.placeholder = ''", onblur: "this.placeholder = 'long'", class: "eventnewform" %>
	      <%= event.text_field :lat, :placeholder => "lat", onfocus: "this.placeholder = ''", onblur: "this.placeholder = 'lat'", class: "eventnewform" %>
        <%= event.submit "Create Event", class: "margin1t" %>
		  </div>
    <% end %>

<% @events.each do |event| %>
<ul>
	<li><%= event.eventname %></li>
	<li><%= event.startdate %></li>
	<li><%= event.enddate %></li>
	<li><%= event.shortdescription %></li>
	<li><%= event.region %></li>
	<li><%= event.postcode %></li>
	<li><%= event.approved %></li>
	<li><%= link_to 'Finalise', edit_event_path(event) %></li>
</ul>
<% end %>

app/views/admin/listings.html.erb
<% @listings.each do |listing| %>
<ul>
	<li><%= listing.franchisename %></li>
	<li><%= listing.category %></li>
	<li>Registered by <%= listing.fullname %>, <%= listing.jobtitle %></li>
	<li><%= link_to 'Finalise', edit_listing_path(listing) %></li>
</ul>
<% end %>

app/views/admin/moneyzone.html.erb
 <%= form_for(@post) do |post| %>
	 <%= post.label :image %>
   <%= post.text_field :image %>
   <%= post.label :title %>
   <%= post.text_field :title %>
	 <%= post.label :content %>
   <%= post.text_area :content %>
	 <%= post.label :name %>
   <%= post.text_field :name %>
	 <%= post.label :website %>
   <%= post.text_field :website %>
	 <%= post.label :approved %>
   <%= post.text_field :approved %>
   <%= post.submit %>
 <% end %>

app/views/admin/overview.html.erb
<h1>Admin#overview</h1>
<p>Find me in app/views/admin/overview.html.erb</p>

app/views/partials/_contactform.html.erb
<%= form_for @contact, :url => {:controller => "footerlinks", :action => :contactcreate } do |contact|%>
	<%= contact.text_field :fullname, :placeholder => "Full name", onfocus: "this.placeholder = ''", onblur: "this.placeholder = 'Full name'" %>
	<%= contact.text_field :email, :placeholder => "Email", onfocus: "this.placeholder = ''", onblur: "this.placeholder = 'Email'" %>
	<%= contact.text_area :query, class: "height15", :placeholder => "Query", onfocus: "this.placeholder = ''", onblur: "this.placeholder = 'Query'" %>
	<%= contact.text_field :nickname, class: "displaynone" %>
  <%= contact.check_box :toc %>
  <%= contact.label :toc, "I agree to the UKF terms and conditions", class: "textup" %>
	<%= contact.submit "Send", class: "font08 textup ubuntu white weight700 registrationsubmit" %>
<% end %>