config/routes.rb
Rails.application.routes.draw do

  get 'insights/dashboard'

  get 'insights/leads'

  get 'insights/editlisting'

  devise_for :franchises, :controllers => {:registrations => "franchises/registrations"}
  devise_for :users, :controllers => {:registrations => "users/registrations"}

  get 'footerlinks/editlisting'
  get 'footerlinks/franchisorinfo'
  get 'footerlinks/aboutus'
  get 'footerlinks/contactus'
  get 'footerlinks/toc'
  post 'footerlinks/contactcreate'

  get '/sitemap.xml.gz', to: 'sitemaps#show'
  
  get 'lead_form/new'
  get 'lead_form/create'

  get 'blog', to: 'posts#index'
  get 'posts/new'
  get 'posts/edit'
  get 'posts/show'

  get 'events/', to: 'events#index'
  get 'events/new'
  get 'events/show'
  get 'events/edit'

  get 'industry/index'
  get 'industry/accounting'
  get 'industry/agriculture'
  get 'industry/automotive'
  get 'industry/beverage'
  get 'industry/B2B'
  get 'industry/cafeandcoffee'
  get 'industry/care'
  get 'industry/chemical'
  get 'industry/childrenandbabies'
  get 'industry/cleaning'
  get 'industry/communications'
  get 'industry/computers'
  get 'industry/construction'
  get 'industry/consultancy'
  get 'industry/logistics'
  get 'industry/educationandtraining'
  get 'industry/electrical'
  get 'industry/entertainment'
  get 'industry/enviromental'
  get 'industry/estateagents'
  get 'industry/fashion'
  get 'industry/financial'
  get 'industry/food'
  get 'industry/health'
  get 'industry/hirerental'
  get 'industry/hospitality'
  get 'industry/indoorpropertyservices'
  get 'industry/outdoorpropertyservices'
  get 'industry/internet'
  get 'industry/legal'
  get 'industry/manafacture'
  get 'industry/pets'
  get 'industry/promotional'
  get 'industry/print'
  get 'industry/repairandmaintenance'

  get 'industry/investment1'
  get 'industry/investment2'
  get 'industry/investment3'
  get 'industry/investment4'

  get 'admin/overview'
  get 'admin/listings'
  get 'admin/events'
  get 'admin/moneyzone'

  resources :listings, :path => "franchise" do
     member do
       get :leadcreate
       post :storycreate
     end
  end

  resources :admin

  resources :posts, :path => "blog"
  post 'posts/subscribe' => 'posts#subscribe'

  resources :events

  devise_for :admins

  root to: 'home#index'

  get 'home/index'
  get 'home/search'
  get 'comingsoon', to: "home#comingsoon"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates_acceptance_of :toc, :on => :create, :accept => true
	validates :fullname, :email, :query, presence: true
	validates :fullname, :email, :query, length: {minimum: 0, maximum: 5000}
end

app/models/event.rb
class Event < ActiveRecord::Base
  extend FriendlyId
  friendly_id :eventname, use: :slugged
end

app/models/franchise.rb
class Franchise < ActiveRecord::Base
	has_one :listing
 	accepts_nested_attributes_for :listing
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/lead.rb
class Lead < ActiveRecord::Base
	belongs_to :listing
end

app/models/listing.rb
require 'elasticsearch/model'

class Listing < ActiveRecord::Base
  belongs_to :franchise, :dependent => :delete
  has_many :leads
  has_many :stories

  extend FriendlyId
  friendly_id :franchisename, use: :slugged

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

	is_impressionable



def self.search(query)
  __elasticsearch__.search(
    {
      query: {
        multi_match: {
          query: query,
          fields: ['franchisename^10', 'longdescription']
        }
      }
    }
  )
end

end

# Delete the previous articles index in Elasticsearch
Listing.__elasticsearch__.client.indices.delete index: Listing.index_name rescue nil
 
# Create the new index with the new mapping
Listing.__elasticsearch__.client.indices.create \
  index: Listing.index_name,
  body: { settings: Listing.settings.to_hash, mappings: Listing.mappings.to_hash }
 
# Index all article records from the DB to Elasticsearch
Listing.import

app/models/post.rb
class Post < ActiveRecord::Base

  extend FriendlyId
  friendly_id :title, use: :slugged

	is_impressionable

end

app/models/story.rb
class Story < ActiveRecord::Base
	belongs_to :listing
	
	validates_acceptance_of :toc, :on => :create, :accept => true
  validates :fullname, :email, :jobrole, :story, presence: true
  validates :story, uniqueness: true
  validates :fullname, :email, :jobrole, length: { minimum: 5, maximum: 150 }
  validates :story, length: { minimum: 150, maxium: 360 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
   before_filter :authenticate_admin!,
    :only => [:overview, :listings, :events, :moneyzone]

  def overview
  end

  def listings
  	@listings = Listing.where(approved: false).reverse
  end

  def events
    @newevent = Event.new
  	@events = Event.where(approved: false).reverse
  end

  def moneyzone
    @post = Post.new
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def robots
  end

  def index
  	@latest = Listing.where(approved: true, topfranchise: true).order('created_at DESC').limit(5)
  	@spotlight = Listing.where(approved: true, spotlight: true).order('created_at DESC').limit(3)
  	@events = Event.all
    @post1 = Post.where(:approved => true).last
    @additional1 = Post.where(:approved => true).offset(1).last
    @additional2 = Post.where(:approved => true).offset(2).last
    @additional3 = Post.where(:approved => true).offset(3).last
  end

  def search
    @query = params[:search]
    if params[:search].nil?
      @result = Listing.search.all.records
    else
      @result = Listing.search(params[:search]).records
    end
  end

  def comingsoon
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/footerlinks_helper.rb
module FooterlinksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/industry_helper.rb
module IndustryHelper
end

app/helpers/insights_helper.rb
module InsightsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/panel_helper.rb
module PanelHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sitemaps_helper.rb
module SitemapsHelper
end

app/views/home/comingsoon.html.erb
<%
meta title: ["Coming Soon", "UK Franchise"]
%>

<div class="row padding10v whitebg">
	<div class="large-24 columns text-center">
		<h1 class="weight500">Coming Soon</h1>
		<p>This feature is currently in development and will be released shortly.</p>
		<a href="<%= root_path %>"><span style="font-size: 0.7rem;
background: #328ce7;
color: #fff;
padding: 0.4rem 2rem;
border-radius: 3px;">RETURN HOME</span></a>
	</div>
</div>

app/views/home/search.html.erb
<%
meta title: ["Results for #{@query}", "UK Franchise"],
     description: "Search through all of the UK's franchise brands easily and quickly.",
     keywords: ["#{@query}", "search", "results"]
%>

<div class="row bluebg padding2t1b">
	<div class="large-24 columns content2">
		<h1 class="white weight700 ubuntu textup font16">Results for "<%= @query %>"</h1>
	</div>
</div>


<% @result.each_slice(3) do |row_result| %>
<div class="row padding3t content lightergreybg">
	<% row_result.each do |result| %>
		<div class="large-8 columns content">
			<a href="<%= listing_path(result) %>">
				<div class="singlelisting">
					<div class="text-center">
						<div style="border-bottom: 2px solid <%= result.hexbg %>"><img src="<%= result.logourl %>" class="padding1v listinglogo"></div>
					</div>
					<p class="font08 content3 lightergreybg padding1v margin0b"><%= truncate("#{result.longdescription}".gsub(/<[^<>]*>/, " "), :length => 250, :separator => '', :omission => "") %></p>
					<div class="row lightgreybg padding05v">
						<div class="large-24 columns text-center">
							<h4 class="font08 margin0b margin0t"><%= image_tag('listingicon1.png', class: "listingicon") %><span class="listingicontext"><%= result.franchisename %></span></h4>
						</div>
					</div>
					<p class="text-center textup white margin0b padding05v font07 viewfranchiseprofile">VIEW FRANCHISE PROFILE</p>
				</div>
			</a>
		</div>
	<% end %>
</div>
<% end %>