config/routes.rb
Rails.application.routes.draw do

  get 'insights/dashboard'

  get 'insights/leads'

  get 'insights/editlisting'

  devise_for :franchises, :controllers => {:registrations => "franchises/registrations"}
  devise_for :users, :controllers => {:registrations => "users/registrations"}

  get 'footerlinks/editlisting'
  get 'footerlinks/franchisorinfo'
  get 'footerlinks/aboutus'
  get 'footerlinks/contactus'
  get 'footerlinks/toc'
  post 'footerlinks/contactcreate'

  get '/sitemap.xml.gz', to: 'sitemaps#show'
  
  get 'lead_form/new'
  get 'lead_form/create'

  get 'blog', to: 'posts#index'
  get 'posts/new'
  get 'posts/edit'
  get 'posts/show'

  get 'events/', to: 'events#index'
  get 'events/new'
  get 'events/show'
  get 'events/edit'

  get 'industry/index'
  get 'industry/accounting'
  get 'industry/agriculture'
  get 'industry/automotive'
  get 'industry/beverage'
  get 'industry/B2B'
  get 'industry/cafeandcoffee'
  get 'industry/care'
  get 'industry/chemical'
  get 'industry/childrenandbabies'
  get 'industry/cleaning'
  get 'industry/communications'
  get 'industry/computers'
  get 'industry/construction'
  get 'industry/consultancy'
  get 'industry/logistics'
  get 'industry/educationandtraining'
  get 'industry/electrical'
  get 'industry/entertainment'
  get 'industry/enviromental'
  get 'industry/estateagents'
  get 'industry/fashion'
  get 'industry/financial'
  get 'industry/food'
  get 'industry/health'
  get 'industry/hirerental'
  get 'industry/hospitality'
  get 'industry/indoorpropertyservices'
  get 'industry/outdoorpropertyservices'
  get 'industry/internet'
  get 'industry/legal'
  get 'industry/manafacture'
  get 'industry/pets'
  get 'industry/promotional'
  get 'industry/print'
  get 'industry/repairandmaintenance'

  get 'industry/investment1'
  get 'industry/investment2'
  get 'industry/investment3'
  get 'industry/investment4'

  get 'admin/overview'
  get 'admin/listings'
  get 'admin/events'
  get 'admin/moneyzone'

  resources :listings, :path => "franchise" do
     member do
       get :leadcreate
       post :storycreate
     end
  end

  resources :admin

  resources :posts, :path => "blog"
  post 'posts/subscribe' => 'posts#subscribe'

  resources :events

  devise_for :admins

  root to: 'home#index'

  get 'home/index'
  get 'home/search'
  get 'comingsoon', to: "home#comingsoon"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates_acceptance_of :toc, :on => :create, :accept => true
	validates :fullname, :email, :query, presence: true
	validates :fullname, :email, :query, length: {minimum: 0, maximum: 5000}
end

app/models/event.rb
class Event < ActiveRecord::Base
  extend FriendlyId
  friendly_id :eventname, use: :slugged
end

app/models/franchise.rb
class Franchise < ActiveRecord::Base
	has_one :listing
 	accepts_nested_attributes_for :listing
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/lead.rb
class Lead < ActiveRecord::Base
	belongs_to :listing
end

app/models/listing.rb
require 'elasticsearch/model'

class Listing < ActiveRecord::Base
  belongs_to :franchise, :dependent => :delete
  has_many :leads
  has_many :stories

  extend FriendlyId
  friendly_id :franchisename, use: :slugged

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

	is_impressionable



def self.search(query)
  __elasticsearch__.search(
    {
      query: {
        multi_match: {
          query: query,
          fields: ['franchisename^10', 'longdescription']
        }
      }
    }
  )
end

end

# Delete the previous articles index in Elasticsearch
Listing.__elasticsearch__.client.indices.delete index: Listing.index_name rescue nil
 
# Create the new index with the new mapping
Listing.__elasticsearch__.client.indices.create \
  index: Listing.index_name,
  body: { settings: Listing.settings.to_hash, mappings: Listing.mappings.to_hash }
 
# Index all article records from the DB to Elasticsearch
Listing.import

app/models/post.rb
class Post < ActiveRecord::Base

  extend FriendlyId
  friendly_id :title, use: :slugged

	is_impressionable

end

app/models/story.rb
class Story < ActiveRecord::Base
	belongs_to :listing
	
	validates_acceptance_of :toc, :on => :create, :accept => true
  validates :fullname, :email, :jobrole, :story, presence: true
  validates :story, uniqueness: true
  validates :fullname, :email, :jobrole, length: { minimum: 5, maximum: 150 }
  validates :story, length: { minimum: 150, maxium: 360 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
   before_filter :authenticate_admin!,
    :only => [:overview, :listings, :events, :moneyzone]

  def overview
  end

  def listings
  	@listings = Listing.where(approved: false).reverse
  end

  def events
    @newevent = Event.new
  	@events = Event.where(approved: false).reverse
  end

  def moneyzone
    @post = Post.new
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
     before_filter :authenticate_admin!,
    :only => [:edit, :update]

  def index
    @events = Event.all
  end

  def create
    if params[:event][:nickname].blank?
    	@event = Event.create(event_params)
    	respond_to do |format|
      	if @event.save
          	format.html { redirect_to root_path, notice: 'Success! Your event has been submitted for approval.' }
          	format.json {  }
      	else
          	format.html { redirect_to root_path, alert: 'Oops! It seems something went wrong in your submission, please try again.'  }
          	format.json {  }
      	end
      end
    else
      redirect_to :back, alert: "Oops! It looks like you have entered something incorrectly, please try again."
    end
  end
  
  def show
    @event = Event.friendly.find(params[:id])
    @metadesc = @event.shortdescription.truncate(250)
  end

  def edit
    @event = Event.friendly.find(params[:id])
  end

  def update
    @event = Event.friendly.find(params[:id])
    if @event.update(event_params)
      redirect_to admin_events_path, notice: 'Event was successfully updated.'
    else
      redirect_to admin_events_path, alert: 'Event was not successfully updated.'
    end
  end

  def event_params
      params.require(:event).permit(:eventname, :startdate, :enddate, :shortdescription, :region, :website, :postcode, :toc, :approved, :nickname, :lat, :long)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def robots
  end

  def index
  	@latest = Listing.where(approved: true, topfranchise: true).order('created_at DESC').limit(5)
  	@spotlight = Listing.where(approved: true, spotlight: true).order('created_at DESC').limit(3)
  	@events = Event.all
    @post1 = Post.where(:approved => true).last
    @additional1 = Post.where(:approved => true).offset(1).last
    @additional2 = Post.where(:approved => true).offset(2).last
    @additional3 = Post.where(:approved => true).offset(3).last
  end

  def search
    @query = params[:search]
    if params[:search].nil?
      @result = Listing.search.all.records
    else
      @result = Listing.search(params[:search]).records
    end
  end

  def comingsoon
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/footerlinks_helper.rb
module FooterlinksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/industry_helper.rb
module IndustryHelper
end

app/helpers/insights_helper.rb
module InsightsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/panel_helper.rb
module PanelHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sitemaps_helper.rb
module SitemapsHelper
end

app/views/events/edit.html.erb
<%= form_for(@event) do |event| %>
<%= event.text_field :eventname, :placeholder => "Event Name", onfocus: "this.placeholder = ''", onblur: "this.placeholder = 'Event Name'", class: "eventnewform" %>
<div class="row">
	<div class="large-11 columns">
    <%= event.text_field :startdate, :placeholder => "Start Date (DD/MM/YYYY)", onfocus: "this.placeholder = ''", onblur: "this.placeholder = 'Start Date (DD/MM/YYYY)'", class: "eventnewform" %>
  </div>
  <div class="large-2 columns">
  	<br>
  </div>
  <div class="large-11 columns">
    <%= event.text_field :enddate %>
  </div>
  <%= event.text_area :shortdescription %>
  <%= event.text_field :region %>
  <%= event.text_field :postcode %>
  <%= event.text_field :website %>
  <%= event.text_field :approved %>
  <%= event.text_field :lat %>
  <%= event.text_field :long %>
  <%= event.submit "Update", class: "margin1t" %>
</div>
<% end %>

app/views/events/index.html.erb
<%
meta title: ["Franchise Events", "UK Franchise"],
     description: "The UK's franchise events can be a great tool for discovering franchise opportunities and gaining insight into their day-to-day activities and potential.",
     keywords: ["events", "exhibitions", "discover", "locations"]
%>



<div class="row padding2v eventsbg">
  <div class="large-14 medium-14 columns content2 eventheader">
    <%= image_tag('eventslogo.png', class: "eventslogo") %>
  </div>
  <div class="large-10 medium-10 columns content2 text-right">
    <div class="row valign-normal right">
    	<%= form_tag('/posts/subscribe', method: "post", id: "subscribe") do%>
        <div class="large-18 medium-18 columns text-right mailer">
        	<%= email_field(:email, :email, {id: "mailersub", placeholder: "Sign up to our newsletter", onfocus: "this.placeholder = ''", onblur: "this.placeholder = 'Sign up to our newsletter'" }) %>
        </div>
        <div class="large-6 medium-6 columns text-right mailer">
	        <%= submit_tag("Submit", id: "mailersubmit", class: "ubuntu") %>
        </div>
      <% end %>
    </div>
  </div>
</div>


<div class="row">
<% @events.in_groups_of(2, false) do |row_event| %>
	<div class="row padding1v marginminus04h">
		<% for event in row_event %>
  		<div class="large-12 columns content1">
				<%= link_to event_path(event), 'data-no-turbolink' => true do %>
					<div class="singleevent">
						<h3 class="font11 padding15t1b content"><%= event.eventname %></h3>
						<p class="text-center textup margin0b content dateline"><%= event.startdate %> to <%= event.enddate %></p>
						<p class="font09 padding1v content margin0b"><%= truncate("#{event.shortdescription}".gsub(/<[^<>]*>/, " "), :length => 250, :separator => '', :omission => "") %></p>
						<p class="text-center textup margin0b content moreline font08">MORE INFORMATION</p>
					</div>
        <% end %>
      </div>
    <% end %>
	</div>
<% end %>
</div>

<div class="row">
	<div class="large-24 columns padding15v">
	</div>
</div>

<script type="text/javascript">
    (function() {

        $(function() {


          $(function() {
            $('.row1').matchHeight();
          });

          $(function() {
            $('.mailer').matchHeight();
          });
          
        });

    })();
</script>